### PR TITLE
Fixes to centimeterPerYear, millimeterPerDay, and molePerHectare

### PR DESCRIPTION
**Pull request by maier-m**

### CODE REVIEW

**Comment by mbjones** [comment]
Thanks, @maier-m -- appreciate this.  My only comment is I wonder if the removal of the whitespace on `millimeterPerDay ` is backwards compatible.  I'd like to see a test document added to tests that uses the standardUnit with the space like `<standardUnit>millimeterPerDay </standardUnit>` and then verify that the document still validates under the new schema.  Could you make those changes and we'll see how the validation tests go in Travis?  Note that there is also an enumeration of standardUnits in `eml-unitTypeDefinitions.xsd` that should be updated as well for any name changes.

**Comment by maier-m** [comment]
OK.
- I think `millimeterPerDay` is a new unit and so shouldn't cause problems with backward compatibility?
- It doesn't look like the `eml-unitTypeDefinitions.xsd` enumeration was updated with the addition of units in the previous commit. Should I update with those units as well?
- I'm sorry I am a little unclear on how to incorporate a validation test in this repo. Can you point me to an example?

**Comment by mbjones** [comment]
OK, if its a new unit then fixing the spaces makes sense.  But yes, we should go ahead and add all of the units to the enumeration.

For testing, we check that all of the xml files in `src/test/resources/` are schema valid and pass the EMLParser checks.  So, adding the use of the unit to one of the test files in that directory will tell you whether it validates or not.  You can run those tests locally on your machine before you commit by running `ant test` in the root of the EML directory (assuming you have the required software installed).

**Comment by maier-m** [comment]
these should now be covered in https://github.com/NCEAS/eml/pull/295

**Pull request closed without merging**
